language: php

php:
  - 5.4
#  - 5.5
#  - 5.6
#  - 7.0
#  - nightly

env:
  - DOWNLOAD_VERSION=1210FC6de
#  - DOWNLOAD_VERSION=1170FC8de
#  - DOWNLOAD_VERSION=1150fc9de

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: nightly

sudo: true

before_install:
  - sudo apt-get update -qq 
  - sudo apt-get install aria2 curl -y
  - travis_retry export DOWNLOAD_LINK=$(phantomjs --ssl-protocol=tlsv1 download.js | tail -1 | grep http)
  - travis_retry aria2c -x 16 ${DOWNLOAD_LINK}
  - DOWNLOAD_FILE=$(ls iif*.tar)
  - echo ${DOWNLOAD_FILE}
  - sudo chmod +x *.sh
  - sudo ./informix_install.sh ${DOWNLOAD_FILE}
  - rm ${DOWNLOAD_FILE} -f
  - sudo ./informix_start.sh
  - export INFORMIXDIR=/opt/IBM/informix
  - git clone https://git.php.net/repository/pecl/database/pdo_informix.git
  - (cd pdo_informix/; phpize && ./configure --with-pdo-informix=${INFORMIXDIR} && make && sudo make install)
  - echo "extension=pdo_informix.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m | grep -i pdo
  - php connect.php

script:
  - echo Hola

after_failure:
  - cat /home/informix/data/logs/online.log
