language: php

php:
  - 5.4

sudo: true

before_install:
  - sudo apt-get update -qq 
  - sudo apt-get install aria2 curl -y
  - DOWNLOAD_LINK=$(curl --url https://raw.githubusercontent.com/wiki/edgardmessias/informix-travis/informix-link-server.md -s | tail -1) ; echo ${DOWNLOAD_LINK} ; aria2c -x 16 ${DOWNLOAD_LINK} ; ls -l
  - sudo chmod +x *.sh
  - sudo ./informix_install.sh iif.12.10.FC5DE.linux-x86_64.tar

script:
  - echo Hola
